name: trufflehog-scan
run-name: ${{ github.actor }}
on: [push]
jobs:
  runs-trufflehog:
    runs-on: ['self-hosted-desktop']
    steps:
      - run: podman run -it trufflesecurity/trufflehog:latest github --org=Toyota-Connected-India --include-forks --json